"""add new tables

Revision ID: 0115318d3c8a
Revises: c84be1641910
Create Date: 2024-04-26 18:59:00.082061

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0115318d3c8a'
down_revision: Union[str, None] = 'c84be1641910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_info',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('total_monthly_income', sa.Integer(), nullable=True),
    sa.Column('employment_status', sa.String(), nullable=True),
    sa.Column('have_loan', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_info_id'), 'financial_info', ['id'], unique=False)
    op.create_index(op.f('ix_financial_info_user_id'), 'financial_info', ['user_id'], unique=False)
    op.create_table('loan_providers',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('is_bank', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_providers_id'), 'loan_providers', ['id'], unique=False)
    op.create_index(op.f('ix_loan_providers_name'), 'loan_providers', ['name'], unique=False)
    op.create_table('loans',
    sa.Column('intrest_rate', sa.Integer(), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('loan_provider_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sharia_compliant', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    op.add_column('products', sa.Column('neighborhood', sa.String(), nullable=True))
    op.add_column('products', sa.Column('os_listing_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'os_listing_id')
    op.drop_column('products', 'neighborhood')
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    op.drop_index(op.f('ix_loan_providers_name'), table_name='loan_providers')
    op.drop_index(op.f('ix_loan_providers_id'), table_name='loan_providers')
    op.drop_table('loan_providers')
    op.drop_index(op.f('ix_financial_info_user_id'), table_name='financial_info')
    op.drop_index(op.f('ix_financial_info_id'), table_name='financial_info')
    op.drop_table('financial_info')
    # ### end Alembic commands ###
